-- =====================================================
-- 添加元数据字段迁移脚本
-- 为 ATTACH_CATALOGUE_TEMPLATES 表添加 META_FIELDS 字段
-- =====================================================

DO $$ 
BEGIN
    RAISE NOTICE '开始执行元数据字段迁移...';
    
    -- 检查表是否存在
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'APPATTACH_CATALOGUE_TEMPLATES') THEN
        RAISE EXCEPTION '表 APPATTACH_CATALOGUE_TEMPLATES 不存在';
    END IF;
    
    -- 检查字段是否已存在
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'APPATTACH_CATALOGUE_TEMPLATES' AND column_name = 'META_FIELDS') THEN
        RAISE NOTICE '字段 META_FIELDS 已存在，跳过添加';
    ELSE
        -- 添加元数据字段
        ALTER TABLE "APPATTACH_CATALOGUE_TEMPLATES" 
        ADD COLUMN "META_FIELDS" jsonb DEFAULT '[]'::jsonb;
        
        RAISE NOTICE '已添加字段 META_FIELDS';
        
        -- 添加字段注释
        COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."META_FIELDS" IS '元数据字段集合（JSONB格式，存储元数据字段信息）';
        
        RAISE NOTICE '已添加字段注释';
    END IF;
    
    -- 验证字段添加结果
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'APPATTACH_CATALOGUE_TEMPLATES' AND column_name = 'META_FIELDS') THEN
        RAISE NOTICE '元数据字段迁移完成';
    ELSE
        RAISE EXCEPTION '元数据字段迁移失败';
    END IF;
    
EXCEPTION WHEN OTHERS THEN
    RAISE EXCEPTION '元数据字段迁移过程中发生错误：%', SQLERRM;
END $$;

-- 创建索引（在事务外执行）
-- 注意：CREATE INDEX CONCURRENTLY 不能在事务块中运行
-- 请在迁移脚本执行完成后单独运行以下语句

/*
-- 为元数据字段创建GIN索引（用于JSON查询）
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_ATTACH_CATALOGUE_TEMPLATES_META_FIELDS" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN ("META_FIELDS");

-- 为元数据字段的常用查询路径创建索引
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_ATTACH_CATALOGUE_TEMPLATES_META_FIELDS_ENTITY_TYPE" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN (("META_FIELDS"->>'EntityType'));

CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_ATTACH_CATALOGUE_TEMPLATES_META_FIELDS_DATA_TYPE" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN (("META_FIELDS"->>'DataType'));

CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_ATTACH_CATALOGUE_TEMPLATES_META_FIELDS_IS_REQUIRED" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN (("META_FIELDS"->>'IsRequired'));

CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_ATTACH_CATALOGUE_TEMPLATES_META_FIELDS_IS_ENABLED" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN (("META_FIELDS"->>'IsEnabled'));

CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_ATTACH_CATALOGUE_TEMPLATES_META_FIELDS_GROUP" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN (("META_FIELDS"->>'Group'));

-- 为元数据字段的标签创建索引
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_ATTACH_CATALOGUE_TEMPLATES_META_FIELDS_TAGS" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN (("META_FIELDS"->'Tags'));
*/
