-- =====================================================
-- AttachCatalogueTemplate 表迁移脚本
-- =====================================================

-- 创建模板表
CREATE TABLE IF NOT EXISTS "APPATTACH_CATALOGUE_TEMPLATES" (
    "ID" uuid NOT NULL,
    "TEMPLATE_NAME" character varying(256) NOT NULL,
    "VERSION" integer NOT NULL DEFAULT 1,
    "IS_LATEST" boolean NOT NULL DEFAULT true,
    "ATTACH_RECEIVE_TYPE" integer NOT NULL,
    "NAME_PATTERN" character varying(512),
    "RULE_EXPRESSION" text,
    "SEMANTIC_MODEL" character varying(128),
    "IS_REQUIRED" boolean NOT NULL DEFAULT false,
    "SEQUENCE_NUMBER" integer NOT NULL DEFAULT 0,
    "IS_STATIC" boolean NOT NULL DEFAULT false,
    "PARENT_ID" uuid,
    "TEMPLATE_TYPE" integer NOT NULL DEFAULT 99,
    "TEMPLATE_PURPOSE" integer NOT NULL DEFAULT 1,
    "TEXT_VECTOR" double precision[],
    "VECTOR_DIMENSION" integer NOT NULL DEFAULT 0,
    "EXTRA_PROPERTIES" text,
    "CONCURRENCY_STAMP" character varying(40),
    "CREATION_TIME" timestamp without time zone NOT NULL,
    "CREATOR_ID" uuid,
    "LAST_MODIFICATION_TIME" timestamp without time zone,
    "LAST_MODIFIER_ID" uuid,
    "IS_DELETED" boolean NOT NULL DEFAULT false,
    "DELETER_ID" uuid,
    "DELETION_TIME" timestamp without time zone,
    CONSTRAINT "PK_ATTACH_CATALOGUE_TEMPLATES" PRIMARY KEY ("ID")
);

-- 创建索引
CREATE INDEX IF NOT EXISTS "UK_ATTACH_CATALOGUE_TEMPLATES_NAME_VERSION" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("TEMPLATE_NAME", "VERSION") 
WHERE "IS_DELETED" = false;

CREATE INDEX IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_NAME_LATEST" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("TEMPLATE_NAME", "IS_LATEST") 
WHERE "IS_DELETED" = false AND "IS_LATEST" = true;

CREATE INDEX IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_PARENT_ID" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("PARENT_ID");

CREATE INDEX IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_SEQUENCE" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("SEQUENCE_NUMBER");

-- 创建模板标识索引
CREATE INDEX IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_TYPE" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("TEMPLATE_TYPE") 
WHERE "IS_DELETED" = false;

CREATE INDEX IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_PURPOSE" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("TEMPLATE_PURPOSE") 
WHERE "IS_DELETED" = false;

-- 创建复合模板标识索引
CREATE INDEX IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_IDENTIFIER_COMPOSITE" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("TEMPLATE_TYPE", "TEMPLATE_PURPOSE") 
WHERE "IS_DELETED" = false;

-- 创建向量维度索引
CREATE INDEX IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_VECTOR_DIM" 
ON "APPATTACH_CATALOGUE_TEMPLATES" ("VECTOR_DIMENSION") 
WHERE "IS_DELETED" = false AND "VECTOR_DIMENSION" > 0;

-- 创建全文搜索索引
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IDX_ATTACH_CATALOGUE_TEMPLATES_FULLTEXT" 
ON "APPATTACH_CATALOGUE_TEMPLATES" USING GIN (
    to_tsvector('chinese_fts', 
        COALESCE("TEMPLATE_NAME", '') || ' ' || 
        COALESCE("NAME_PATTERN", '') || ' ' ||
        COALESCE("RULE_EXPRESSION", '')
    )
);

-- 创建外键约束
ALTER TABLE "APPATTACH_CATALOGUE_TEMPLATES" 
ADD CONSTRAINT "FK_ATTACH_CATALOGUE_TEMPLATES_PARENT" 
FOREIGN KEY ("PARENT_ID") REFERENCES "APPATTACH_CATALOGUE_TEMPLATES" ("ID") 
ON DELETE CASCADE;

-- 添加字段约束
ALTER TABLE "APPATTACH_CATALOGUE_TEMPLATES" 
ADD CONSTRAINT "CK_ATTACH_CATALOGUE_TEMPLATES_VECTOR_DIMENSION" 
CHECK ("VECTOR_DIMENSION" >= 0 AND "VECTOR_DIMENSION" <= 2048);

ALTER TABLE "APPATTACH_CATALOGUE_TEMPLATES" 
ADD CONSTRAINT "CK_ATTACH_CATALOGUE_TEMPLATES_TEMPLATE_TYPE" 
CHECK ("TEMPLATE_TYPE" IN (1, 2, 3, 4, 99));

ALTER TABLE "APPATTACH_CATALOGUE_TEMPLATES" 
ADD CONSTRAINT "CK_ATTACH_CATALOGUE_TEMPLATES_TEMPLATE_PURPOSE" 
CHECK ("TEMPLATE_PURPOSE" IN (1, 2, 3, 4, 99));

-- 添加注释
COMMENT ON TABLE "APPATTACH_CATALOGUE_TEMPLATES" IS '附件分类模板表';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."TEMPLATE_NAME" IS '模板名称';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."VERSION" IS '模板版本号';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."IS_LATEST" IS '是否为最新版本';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."ATTACH_RECEIVE_TYPE" IS '附件类型';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."NAME_PATTERN" IS '分类名称规则';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."RULE_EXPRESSION" IS '规则引擎表达式';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."SEMANTIC_MODEL" IS 'AI语义匹配模型名称';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."IS_REQUIRED" IS '是否必收';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."SEQUENCE_NUMBER" IS '顺序号';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."IS_STATIC" IS '是否静态';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."PARENT_ID" IS '父模板Id';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."TEMPLATE_TYPE" IS '模板类型：1=项目级,2=阶段级,3=业务分类,4=专业领域,99=通用';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."TEMPLATE_PURPOSE" IS '模板用途：1=分类管理,2=文档管理,3=流程管理,4=权限管理,99=其他';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."TEXT_VECTOR" IS '文本向量（64-2048维）';
COMMENT ON COLUMN "APPATTACH_CATALOGUE_TEMPLATES"."VECTOR_DIMENSION" IS '向量维度';

-- 插入示例数据（可选）
INSERT INTO "APPATTACH_CATALOGUE_TEMPLATES" (
    "ID", "TEMPLATE_NAME", "VERSION", "IS_LATEST", "ATTACH_RECEIVE_TYPE", 
    "NAME_PATTERN", "RULE_EXPRESSION", "SEMANTIC_MODEL", "IS_REQUIRED", 
    "SEQUENCE_NUMBER", "IS_STATIC", "PARENT_ID", "TEMPLATE_TYPE", 
    "TEMPLATE_PURPOSE", "CREATION_TIME"
) VALUES (
    gen_random_uuid(), '项目级模板-建筑工程', 1, true, 0, 
    '建筑工程_{DateTime:yyyyMMdd}', 
    '{"WorkflowName": "ProjectWorkflow", "Rules": [{"RuleName": "ProjectRule", "Expression": "TemplateType == 1"}]}', 
    'project_construction_model', false, 1, true, null, 1, 1, NOW()
) ON CONFLICT DO NOTHING;

INSERT INTO "APPATTACH_CATALOGUE_TEMPLATES" (
    "ID", "TEMPLATE_NAME", "VERSION", "IS_LATEST", "ATTACH_RECEIVE_TYPE", 
    "NAME_PATTERN", "RULE_EXPRESSION", "SEMANTIC_MODEL", "IS_REQUIRED", 
    "SEQUENCE_NUMBER", "IS_STATIC", "PARENT_ID", "TEMPLATE_TYPE", 
    "TEMPLATE_PURPOSE", "CREATION_TIME"
) VALUES (
    gen_random_uuid(), '阶段级模板-施工图设计', 1, true, 0, 
    '施工图设计_{DateTime:yyyyMMdd}', 
    '{"WorkflowName": "PhaseWorkflow", "Rules": [{"RuleName": "PhaseRule", "Expression": "TemplateType == 2"}]}', 
    'phase_design_model', false, 2, true, null, 2, 1, NOW()
) ON CONFLICT DO NOTHING;

-- 验证表创建
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'APPATTACH_CATALOGUE_TEMPLATES' 
ORDER BY ordinal_position;

-- 验证索引创建
SELECT 
    indexname,
    indexdef
FROM pg_indexes 
WHERE tablename = 'APPATTACH_CATALOGUE_TEMPLATES';

-- 测试查询
SELECT 
    "ID",
    "TEMPLATE_NAME",
    "VERSION",
    "IS_LATEST",
    "TEMPLATE_TYPE",
    "TEMPLATE_PURPOSE",
    "VECTOR_DIMENSION",
    "CREATION_TIME"
FROM "APPATTACH_CATALOGUE_TEMPLATES" 
WHERE "IS_DELETED" = false 
ORDER BY "CREATION_TIME" DESC 
LIMIT 5;

-- 测试模板标识查询
SELECT 
    "TEMPLATE_NAME",
    "TEMPLATE_TYPE",
    "TEMPLATE_PURPOSE"
FROM "APPATTACH_CATALOGUE_TEMPLATES" 
WHERE "IS_DELETED" = false 
  AND "TEMPLATE_TYPE" = 1 
  AND "TEMPLATE_PURPOSE" = 1;
