-- OCR文本块表迁移脚本
-- 用于存储OCR识别结果的文本位置信息

-- 创建OCR文本块表
CREATE TABLE IF NOT EXISTS "APPATTACH_OCR_TEXT_BLOCKS" (
    "ID" uuid NOT NULL,
    "ATTACH_FILE_ID" uuid NOT NULL,
    "TEXT" character varying(4000) NOT NULL,
    "PROBABILITY" numeric(5,4) NOT NULL,
    "PAGE_INDEX" integer NOT NULL,
    "POSITION_DATA" character varying(1000),
    "BLOCK_ORDER" integer NOT NULL,
    "CREATION_TIME" timestamp without time zone NOT NULL,
    "CREATOR_ID" uuid,
    "LAST_MODIFICATION_TIME" timestamp without time zone,
    "LAST_MODIFIER_ID" uuid,
    "IS_DELETED" boolean NOT NULL DEFAULT false,
    "DELETER_ID" uuid,
    "DELETION_TIME" timestamp without time zone,
    CONSTRAINT "PK_APPATTACH_OCR_TEXT_BLOCKS" PRIMARY KEY ("ID")
);

-- 创建索引
CREATE INDEX IF NOT EXISTS "IX_APPATTACH_OCR_TEXT_BLOCKS_ATTACH_FILE_ID" 
ON "APPATTACH_OCR_TEXT_BLOCKS" ("ATTACH_FILE_ID");

CREATE INDEX IF NOT EXISTS "IX_APPATTACH_OCR_TEXT_BLOCKS_TEXT" 
ON "APPATTACH_OCR_TEXT_BLOCKS" ("TEXT");

CREATE INDEX IF NOT EXISTS "IX_APPATTACH_OCR_TEXT_BLOCKS_PROBABILITY" 
ON "APPATTACH_OCR_TEXT_BLOCKS" ("PROBABILITY");

CREATE INDEX IF NOT EXISTS "IX_APPATTACH_OCR_TEXT_BLOCKS_FILE_PAGE_ORDER" 
ON "APPATTACH_OCR_TEXT_BLOCKS" ("ATTACH_FILE_ID", "PAGE_INDEX", "BLOCK_ORDER");

-- 创建文本搜索索引（仅用于基本查询）
CREATE INDEX IF NOT EXISTS "IX_APPATTACH_OCR_TEXT_BLOCKS_TEXT_SEARCH" 
ON "APPATTACH_OCR_TEXT_BLOCKS" ("TEXT");

-- 创建外键约束
ALTER TABLE "APPATTACH_OCR_TEXT_BLOCKS" 
ADD CONSTRAINT "FK_APPATTACH_OCR_TEXT_BLOCKS_ATTACH_FILE_ID" 
FOREIGN KEY ("ATTACH_FILE_ID") 
REFERENCES "APPATTACHFILE" ("ID") 
ON DELETE CASCADE;

-- 添加注释
COMMENT ON TABLE "APPATTACH_OCR_TEXT_BLOCKS" IS 'OCR文本块表，存储OCR识别结果的文本位置信息';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."ID" IS '主键ID';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."ATTACH_FILE_ID" IS '关联的文件ID';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."TEXT" IS '文本内容';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."PROBABILITY" IS '置信度';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."PAGE_INDEX" IS '页面索引（PDF多页时使用）';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."POSITION_DATA" IS '文本位置信息（JSON格式）';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."BLOCK_ORDER" IS '文本块在文档中的位置（用于排序）';
COMMENT ON COLUMN "APPATTACH_OCR_TEXT_BLOCKS"."CREATION_TIME" IS '创建时间';
