-- 字段重命名脚本
-- 将数据库字段名从驼峰命名改为下划线命名，以匹配实体配置

-- 业务字段重命名
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "ATTACHRECEIVETYPE"    TO "ATTACH_RECEIVE_TYPE";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "CATALOGUENAME"        TO "CATALOGUE_NAME";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "REFERENCETYPE"        TO "REFERENCE_TYPE";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "ATTACHCOUNT"          TO "ATTACH_COUNT";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "PAGECOUNT"            TO "PAGE_COUNT";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "ISVERIFICATION"       TO "IS_VERIFICATION";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "VERIFICATIONPASSED"   TO "VERIFICATION_PASSED";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "ISREQUIRED"           TO "IS_REQUIRED";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "SEQUENCENUMBER"       TO "SEQUENCE_NUMBER";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "PARENTID"             TO "PARENT_ID";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "ISSTATIC"             TO "IS_STATIC";

-- 审计字段重命名
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "EXTRAPROPERTIES"      TO "EXTRA_PROPERTIES";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "CONCURRENCYSTAMP"     TO "CONCURRENCY_STAMP";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "CREATIONTIME"         TO "CREATION_TIME";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "CREATORID"            TO "CREATOR_ID";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "LASTMODIFICATIONTIME" TO "LAST_MODIFICATION_TIME";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "LASTMODIFIERID"       TO "LAST_MODIFIER_ID";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "ISDELETED"            TO "IS_DELETED";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "DELETERID"            TO "DELETER_ID";
ALTER TABLE public."APPATTACH_CATALOGUES" RENAME COLUMN "DELETIONTIME"         TO "DELETION_TIME";

-- 验证字段重命名结果
SELECT 
    column_name, 
    data_type, 
    is_nullable
FROM information_schema.columns 
WHERE table_name = 'APPATTACH_CATALOGUES' 
ORDER BY column_name;

-- 清理旧的全文搜索向量字段（如果存在）
DO $$
BEGIN
    -- 如果SEARCH_VECTOR字段存在，则删除（不再需要）
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'APPATTACH_CATALOGUES' 
        AND column_name = 'SEARCH_VECTOR'
    ) THEN
        ALTER TABLE "APPATTACH_CATALOGUES" DROP COLUMN "SEARCH_VECTOR";
        RAISE NOTICE 'SEARCH_VECTOR字段已删除（不再需要）';
    ELSE
        RAISE NOTICE 'SEARCH_VECTOR字段不存在，无需删除';
    END IF;
END $$;

-- 创建全文搜索索引（直接基于字段）
CREATE INDEX IF NOT EXISTS "idx_attach_catalogue_name_fts" 
ON "APPATTACH_CATALOGUES" 
USING GIN (to_tsvector('chinese_fts', "CATALOGUE_NAME"));

-- 验证索引
SELECT 
    indexname, 
    indexdef
FROM pg_indexes 
WHERE tablename = 'APPATTACH_CATALOGUES' 
AND indexname LIKE '%fts%';
