name: Multi-package NuGet Attachment

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.104'

    - name: Build and pack NuGet packages
      run: |
        version=$(echo "${{ github.event.release.tag_name }}" | cut -c 2-)
        echo "Setting version to $version"
        dotnet build src/Hx.Abp.Attachment.Application/Hx.Abp.Attachment.Application.csproj -c Release
        dotnet pack src/Hx.Abp.Attachment.Application/Hx.Abp.Attachment.Application.csproj -c Release -o ./src/Hx.Abp.Attachment.Application /p:PackageVersion=$version

        dotnet build src/Hx.Abp.Attachment.Application.Contracts/Hx.Abp.Attachment.Application.Contracts.csproj -c Release
        dotnet pack src/Hx.Abp.Attachment.Application.Contracts/Hx.Abp.Attachment.Application.Contracts.csproj -c Release -o ./src/Hx.Abp.Attachment.Application.Contracts /p:PackageVersion=$version

        dotnet build src/Hx.Abp.Attachment.Domain/Hx.Abp.Attachment.Domain.csproj -c Release
        dotnet pack src/Hx.Abp.Attachment.Domain/Hx.Abp.Attachment.Domain.csproj -c Release -o ./src/Hx.Abp.Attachment.Domain /p:PackageVersion=$version

        dotnet build src/Hx.Abp.Attachment.Dmain.Shared/Hx.Abp.Attachment.Dmain.Shared.csproj -c Release
        dotnet pack src/Hx.Abp.Attachment.Dmain.Shared/Hx.Abp.Attachment.Dmain.Shared.csproj -c Release -o ./src/Hx.Abp.Attachment.Dmain.Shared /p:PackageVersion=$version

        dotnet build src/Hx.Abp.Attachment.EntityFrameworkCore/Hx.Abp.Attachment.EntityFrameworkCore.csproj -c Release
        dotnet pack src/Hx.Abp.Attachment.EntityFrameworkCore/Hx.Abp.Attachment.EntityFrameworkCore.csproj -c Release -o ./src/Hx.Abp.Attachment.EntityFrameworkCore /p:PackageVersion=$version

        dotnet build src/Hx.Abp.Attachment.Application.ArchAI/Hx.Abp.Attachment.Application.ArchAI.csproj -c Release
        dotnet pack src/Hx.Abp.Attachment.Application.ArchAI/Hx.Abp.Attachment.Application.ArchAI.csproj -c Release -o ./src/Hx.Abp.Attachment.Application.ArchAI /p:PackageVersion=$version

        dotnet build src/Hx.Abp.Attachment.Application.ArchAI.Contracts/Hx.Abp.Attachment.Application.ArchAI.Contracts.csproj -c Release
        dotnet pack src/Hx.Abp.Attachment.Application.ArchAI.Contracts/Hx.Abp.Attachment.Application.ArchAI.Contracts.csproj -c Release -o ./src/Hx.Abp.Attachment.Application.ArchAI.Contracts /p:PackageVersion=$version

        cp ./src/Hx.Abp.Attachment.Application/*.nupkg $GITHUB_WORKSPACE
        cp ./src/Hx.Abp.Attachment.Application.Contracts/*.nupkg $GITHUB_WORKSPACE
        cp ./src/Hx.Abp.Attachment.Domain/*.nupkg $GITHUB_WORKSPACE
        cp ./src/Hx.Abp.Attachment.Dmain.Shared/*.nupkg $GITHUB_WORKSPACE
        cp ./src/Hx.Abp.Attachment.EntityFrameworkCore/*.nupkg $GITHUB_WORKSPACE
        cp ./src/Hx.Abp.Attachment.Application.ArchAI/*.nupkg $GITHUB_WORKSPACE
        cp ./src/Hx.Abp.Attachment.Application.ArchAI.Contracts/*.nupkg $GITHUB_WORKSPACE
    - name: Push NuGet packages
      run: |
       dotnet nuget push ./src/Hx.Abp.Attachment.Application/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
       dotnet nuget push ./src/Hx.Abp.Attachment.Application.Contracts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
       dotnet nuget push ./src/Hx.Abp.Attachment.Domain/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
       dotnet nuget push ./src/Hx.Abp.Attachment.Dmain.Shared/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
       dotnet nuget push ./src/Hx.Abp.Attachment.EntityFrameworkCore/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
       dotnet nuget push ./src/Hx.Abp.Attachment.Application.ArchAI/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
       dotnet nuget push ./src/Hx.Abp.Attachment.Application.ArchAI.Contracts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
